# fly.toml app configuration file generated for spring-forest-5496 on 2023-08-07T13:39:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-paper-4638"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
app = "npm run start-prod"

[build]
[build.args]
  NODE_VERSION = "16.19.1"