# fly.toml app configuration file generated for wispy-paper-4638 on 2023-08-07T12:36:16-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-paper-4638"
primary_region = "lax"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
